name: unn_grading
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  # sdk: ^3.5.2
  sdk: ^2.19.2

dependencies:
  dio: ^5.2.1+1
  either_dart: ^1.0.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.6

  dropdown_button2: ^2.3.9
  file_picker: ^8.1.2
  path_provider: ^2.1.4
  
  go_router: ^14.3.0

  menu_bar: ^0.5.3
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding
      path: plugins/window_size

  pluto_grid: ^7.0.2
  pluto_grid_export: ^1.0.6
  
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
